# Generated by Django 3.1.4 on 2020-12-01 11:11

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbr', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_id', models.CharField(default='', max_length=10)),
                ('sname', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Teacher_id', models.CharField(default='', max_length=10)),
                ('name', models.CharField(max_length=40)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.user')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAttandanceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.subject')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.teacher'),
        ),
        migrations.CreateModel(
            name='StudentAttendanceTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject1', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject1', to='collegeportal.subjectattandancetable')),
                ('subject2', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject2', to='collegeportal.subjectattandancetable')),
                ('subject3', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject3', to='collegeportal.subjectattandancetable')),
                ('subject4', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject4', to='collegeportal.subjectattandancetable')),
                ('subject5', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject5', to='collegeportal.subjectattandancetable')),
                ('subject6', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subject6', to='collegeportal.subjectattandancetable')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photo', models.FileField(upload_to='')),
                ('dob', models.DateField(default='1998-01-01')),
                ('sex', models.CharField(choices=[('M', 'M'), ('F', 'F'), ('OTH', 'OTH')], default='M', max_length=40)),
                ('div', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=40)),
                ('attendance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.studentattendancetable')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.course')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='collegeportal.user')),
            ],
        ),
    ]
