# Generated by Django 3.1.4 on 2020-12-01 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='Teacher_id',
        ),
    ]
