# Generated by Django 3.1.4 on 2020-12-01 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collegeportal', '0002_remove_teacher_teacher_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_id',
        ),
    ]
